server:
  port: 8002

archive:
  access:
    url: http://localhost:8001
  archival-storage:
    url: http://localhost:8002
    store-path: /Users/marco/workspace/study/thesis/archivesystem/data
  data-management:
    url: http://localhost:8003
  ingest:
    url: http://localhost:8004
  blockchain:
    url: http://localhost:8008
    private-key-hex: b4704ab0023b7a141742eaaa63dadf6e459d6c1da579915a23f6a40ca06cf693

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
  packages-to-scan: com.archive.archivalstorage

spring:
  application:
    name: archival-storage
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
