server:
  port: 8004

archive:
  access:
    url: http://localhost:8001
  archival-storage:
    url: http://localhost:8002
  data-management:
    url: http://localhost:8003
  ingest:
    url: http://localhost:8004
    security:
      verify-fingerprint: true
  blockchain:
    private-key-hex: b4704ab0023b7a141742eaaa63dadf6e459d6c1da579915a23f6a40ca06cf693

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
  packages-to-scan: com.archive.ingest

spring:
  application:
    name: ingest
