server:
  port: 8003

archive:
  access:
    url: http://localhost:8001
  archival-storage:
    url: http://localhost:8002
  data-management:
    url: http://localhost:8003
  ingest:
    url: http://localhost:8004

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
  packages-to-scan: com.archive.datamanagement
