server:
  port: 8003

archive:
  access:
    url: http://localhost:8001
  archival-storage:
    url: http://localhost:8002
  data-management:
    url: http://localhost:8003
  ingest:
    url: http://localhost:8004

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
  packages-to-scan: com.archive.datamanagement


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/archive
    username: archive
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  application:
    name: datamanagment
